[build]
  command = "npm install && vite build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 8888
  publish = "dist"
  autoLaunch = true
  framework = "#custom"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/client-ses", "openai", "jose"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://*.supabase.co;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.google.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https://*.unsplash.com https://*.supabase.co https://storage.cloud.google.com https://storage.googleapis.com;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.google.com;
      frame-src 'self' https://*.google.com;
      frame-ancestors 'none';
      upgrade-insecure-requests;
    """
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cache-Control = "public, max-age=31536000"